# Generated by Django 4.0.3 on 2022-03-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_str', models.CharField(max_length=50)),
                ('booked_date', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('attend_status', models.CharField(choices=[('YET', 'YET'), ('YES', 'YES'), ('NO', 'NO')], default='YET', max_length=10)),
                ('count', models.IntegerField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sih_app.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
