# Generated by Django 4.0.3 on 2022-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
