# Generated by Django 4.0.3 on 2022-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0003_alter_ticket_count_alter_ticket_ticket_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
