# Generated by Django 4.0.3 on 2022-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0005_site_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='image_url',
            new_name='image_url_1',
        ),
        migrations.AddField(
            model_name='site',
            name='image_url_2',
            field=models.CharField(default='https://source.unsplash.com/1920x1080/?nature', max_length=300),
        ),
    ]
